 steps:
 # Build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/cldsol0952/github.com/samuelmaissen/lakesidemutual/customer-management-frontend', 'customer-management-frontend/.']
 # Push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/cldsol0952/github.com/samuelmaissen/lakesidemutual/customer-management-frontend']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'run'
   - 'deploy'
   - 'customer-management-frontend'
   - '--image'
   - 'gcr.io/cldsol0952/github.com/samuelmaissen/lakesidemutual/customer-management-frontend'
   - '--region'
   - 'us-central1'
   - --set-env-vars=REACT_APP_CUSTOMER_MANAGEMENT_BACKEND=https://customer-management-backend-bqc53s6dvq-uc.a.run.app/
 images:
 - 'gcr.io/cldsol0952/github.com/samuelmaissen/lakesidemutual/customer-management-frontend'
